export const data = [
  {
    id: 0,
    tipe: "soup",
    img: "foodsoup.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "4.33",
    available: "125 Bowls available",
  },
  {
    id: 1,
    tipe: "soup",
    img: "sopadeconchitas.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "2.99",
    available: "256 Bowls available",
  },
  {
    id: 2,
    tipe: "soup",
    img: "soupCoditos.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "3.55",
    available: "21 Bowls available",
  },
  {
    id: 3,
    tipe: "soup",
    img: "soupPapas.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "7.55",
    available: "30 Bowls available",
  },
  {
    id: 4,
    tipe: "soup",
    img: "soupVerduras.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 5,
    tipe: "soup",
    img: "soupVerduras.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 6,
    tipe: "soup",
    img: "soupVerduras.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 7,
    tipe: "soup",
    img: "soupVerduras.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 8,
    tipe: "soup",
    img: "soupVerduras.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 9,
    tipe: "soup",
    img: "soupVerduras.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 10,
    tipe: "soup",
    img: "soupVerduras.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 11,
    tipe: "soup",
    img: "soupVerduras.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 12,
    tipe: "soup",
    img: "soupVerduras.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 13,
    tipe: "soup",
    img: "soupVerduras.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 14,
    tipe: "soup",
    img: "soupVerduras.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 15,
    tipe: "soup",
    img: "soupVerduras.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 16,
    tipe: "hotDishes",
    img: "hot.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 17,
    tipe: "hotDishes",
    img: "hot2.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 18,
    tipe: "hotDishes",
    img: "hot3.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 19,
    tipe: "hotDishes",
    img: "hot3.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 20,
    tipe: "hotDishes",
    img: "hot3.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 21,
    tipe: "hotDishes",
    img: "hot3.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 22,
    tipe: "hotDishes",
    img: "hot3.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 23,
    tipe: "hotDishes",
    img: "hot3.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 24,
    tipe: "hotDishes",
    img: "hot3.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 25,
    tipe: "hotDishes",
    img: "hot3.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 26,
    tipe: "hotDishes",
    img: "hot3.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 27,
    tipe: "hotDishes",
    img: "hot3.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 28,
    tipe: "hotDishes",
    img: "hot3.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 29,
    tipe: "hotDishes",
    img: "hot3.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 30,
    tipe: "hotDishes",
    img: "hot3.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 31,
    tipe: "hotDishes",
    img: "hot3.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 32,
    tipe: "coldDishes",
    img: "coldFoot1.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 33,
    tipe: "coldDishes",
    img: "coldFoot.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 34,
    tipe: "coldDishes",
    img: "coldFood2.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 35,
    tipe: "coldDishes",
    img: "coldFood2.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 36,
    tipe: "coldDishes",
    img: "coldFood2.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 37,
    tipe: "coldDishes",
    img: "coldFood2.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 38,
    tipe: "coldDishes",
    img: "coldFood2.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 39,
    tipe: "coldDishes",
    img: "coldFood2.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 40,
    tipe: "coldDishes",
    img: "coldFood2.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 41,
    tipe: "coldDishes",
    img: "coldFood2.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 42,
    tipe: "coldDishes",
    img: "coldFood2.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 43,
    tipe: "coldDishes",
    img: "coldFood2.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 44,
    tipe: "coldDishes",
    img: "coldFood2.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 45,
    tipe: "coldDishes",
    img: "coldFood2.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 46,
    tipe: "coldDishes",
    img: "coldFood2.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 47,
    tipe: "coldDishes",
    img: "coldFood2.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 48,
    tipe: "grill",
    img: "grill2.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 49,
    tipe: "grill",
    img: "grill1.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 50,
    tipe: "grill",
    img: "grill.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 51,
    tipe: "grill",
    img: "grill.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 52,
    tipe: "grill",
    img: "grill.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 53,
    tipe: "grill",
    img: "grill.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 54,
    tipe: "grill",
    img: "grill.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 55,
    tipe: "grill",
    img: "grill.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 56,
    tipe: "grill",
    img: "grill.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 57,
    tipe: "grill",
    img: "grill.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 58,
    tipe: "grill",
    img: "grill.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 59,
    tipe: "grill",
    img: "grill.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 60,
    tipe: "grill",
    img: "grill.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 61,
    tipe: "grill",
    img: "grill.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 62,
    tipe: "grill",
    img: "grill.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
  {
    id: 63,
    tipe: "grill",
    img: "grill.jpg",
    description: "Sepacy seasoned seafood nodeles",
    price: "8.96",
    available: "20 Bowls available",
  },
];
